import { useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, CalendarDays, CheckCircle2, ClipboardCheck, ExternalLink, FileText, Play, Plus, RefreshCw, Save, Search, Trash2, Users, X, Youtube } from "lucide-react";

const API_BASE_URL = import.meta.env.VITE_API_URL || "/api";
const currentSession = () => { try { return JSON.parse(localStorage.getItem("careerforge_session")) || null; } catch { return null; } };
const headers = () => ({ "Content-Type": "application/json", "X-User-Id": currentSession()?.id || "" });
async function body(response) { const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || data.detail || (response.status === 503 ? "YouTube is not configured. Add YOUTUBE_API_KEY to .env, then restart the backend." : response.status === 502 ? "The external provider could not complete this request right now." : "Unable to complete that request.")); return data; }
const ActionButton = ({ children, className = "", ...props }) => <button className={`button ${className}`} {...props}>{children}</button>;
const Status = ({ value }) => <span className={`status ${value || ""}`}>{String(value || "unknown").replaceAll("_", " ")}</span>;
const formatDate = (value) => value ? new Date(value).toLocaleDateString() : "—";
const isSafeExternalUrl = (value) => /^https?:\/\//i.test(String(value || "").trim());
const isYouTubeResource = (resource) => /youtube\.com|youtu\.be/i.test(`${resource?.providerName || ""} ${resource?.resourceUrl || ""}`);

function AdminResourceThumbnail({ resource, preview = false }) {
  const isYouTube = isYouTubeResource(resource);
  return <div className={`admin-resource-thumbnail${preview ? " preview" : ""}${isYouTube ? " youtube" : ""}`} aria-hidden="true">
    <span className="admin-resource-thumbnail-fallback">{isYouTube ? <Youtube size={preview ? 28 : 19} /> : <BookOpen size={preview ? 28 : 19} />}</span>
    {resource.thumbnailUrl && <img src={resource.thumbnailUrl} alt="" onError={(event) => { event.currentTarget.style.display = "none"; }} />}
    {isYouTube && <span className="admin-resource-play"><Play size={preview ? 18 : 13} fill="currentColor" /></span>}
    {isYouTube && <span className="admin-resource-youtube-label"><Youtube size={11} /> YouTube</span>}
  </div>;
}

export function AdminProfile() {
  const session = currentSession(); const [profile, setProfile] = useState({ name: session?.name || "", email: session?.email || "", role: "admin" }); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploadingPhoto, setUploadingPhoto] = useState(false);
  useEffect(() => { if (!session?.id) { setNotice("Please sign in again."); setLoading(false); return; } fetch(`${API_BASE_URL}/account/profile`, { headers: headers() }).then(body).then(setProfile).catch((error) => setNotice(error.message)).finally(() => setLoading(false)); }, []);
  const change = (event) => setProfile((current) => ({ ...current, [event.target.name]: event.target.value }));
  const syncSession = (updated) => { const stored = currentSession() || session || {}; localStorage.setItem("careerforge_session", JSON.stringify({ ...stored, name: updated.name, email: updated.email, role: updated.role, profilePhotoUrl: updated.profilePhotoUrl || null })); window.dispatchEvent(new Event("careerforge-session-updated")); };
  async function save(event) { event.preventDefault(); setSaving(true); setNotice(""); try { const updated = await body(await fetch(`${API_BASE_URL}/account/profile`, { method: "PUT", headers: headers(), body: JSON.stringify({ name: profile.name.trim(), email: profile.email.trim() }) })); setProfile(updated); syncSession(updated); setNotice("Profile updated."); } catch (error) { setNotice(error.message); } finally { setSaving(false); } }
  async function uploadPhoto(event) { const photo = event.target.files?.[0]; if (!photo) return; setUploadingPhoto(true); setNotice(""); try { const form = new FormData(); form.append("photo", photo); const updated = await body(await fetch(`${API_BASE_URL}/account/profile/photo`, { method: "POST", headers: { "X-User-Id": currentSession()?.id || "" }, body: form })); setProfile(updated); syncSession(updated); setNotice("Profile photo updated."); } catch (error) { setNotice(error.message); } finally { event.target.value = ""; setUploadingPhoto(false); } }
  const initial = (profile.name || session?.name || "A").slice(0, 1).toUpperCase(); const photoUrl = typeof profile.profilePhotoUrl === "string" && profile.profilePhotoUrl ? (profile.profilePhotoUrl.startsWith("/") ? `${API_BASE_URL}${profile.profilePhotoUrl}` : profile.profilePhotoUrl) : "";
  return <section className="admin-profile-page"><header className="admin-profile-hero"><label className="admin-profile-monogram admin-profile-photo-picker" title="Change profile photo">{photoUrl ? <img src={photoUrl} alt="Admin profile" /> : initial}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={uploadPhoto} disabled={uploadingPhoto} /><em>{uploadingPhoto ? "Uploading" : photoUrl ? "Change" : "Add photo"}</em></label><div><p className="eyebrow"><Users size={14} /> ADMIN ACCOUNT</p><h2>Keep your operator identity current.</h2><p>A small, focused profile for the details shown across your CareerForge workspace.</p></div><span className="admin-profile-access"><Users size={17} /><span><b>Administrator</b><small>Platform access</small></span></span></header><form className="data-form admin-profile-form" onSubmit={save}><div className="admin-profile-form-heading"><div><p className="eyebrow">PROFILE DETAILS</p><h3>Simple account settings</h3><p>Update the name and email connected to this administrator account.</p></div><span>{loading ? "Loading…" : "Active account"}</span></div><div className="form-grid"><label>Display name<input name="name" value={profile.name || ""} onChange={change} maxLength="150" required placeholder="Your name" /></label><label>Email address<input name="email" type="email" value={profile.email || ""} onChange={change} maxLength="190" required placeholder="you@example.com" /></label></div><div className="admin-profile-security"><Users size={17} /><div><b>Account access stays protected</b><span>Your sign-in role is managed by CareerForge and cannot be changed here.</span></div></div>{notice && <p className={notice.includes("updated.") ? "form-success" : "form-error"}>{notice}</p>}<footer><div><b>Save your changes</b><small>Workspace labels update immediately after saving.</small></div><ActionButton type="submit" disabled={loading || saving}><Save size={15} />{saving ? "Saving..." : "Save profile"}</ActionButton></footer></form></section>;
}

export function AdminOverview({ go }) {
  const [counts, setCounts] = useState(null); const [applications, setApplications] = useState([]); const [notice, setNotice] = useState("");
  useEffect(() => { Promise.all([fetch(`${API_BASE_URL}/admin/overview`, { headers: headers() }).then(body), fetch(`${API_BASE_URL}/admin/applications`, { headers: headers() }).then(body)]).then(([overview, items]) => { setCounts(overview); setApplications(items.slice(0, 5)); }).catch((error) => setNotice(error.message)); }, []);
  const cards = [["Registered students", counts?.students, Users], ["Published jobs", counts?.publishedJobs, CheckCircle2], ["Applications", counts?.applications, FileText], ["Assessment attempts", counts?.assessmentAttempts, ClipboardCheck], ["Published resources", counts?.resources, BookOpen], ["Published events", counts?.events, CalendarDays]];
  const launchSteps = [["Jobs live", (counts?.publishedJobs || 0) > 0], ["Resources ready", (counts?.resources || 0) > 0], ["Events planned", (counts?.events || 0) > 0]]; const launchReady = launchSteps.filter(([, done]) => done).length; const launchProgress = counts ? Math.round((launchReady / launchSteps.length) * 100) : 0;
  return <section className="admin-dashboard"><div className="welcome"><div className="admin-overview-copy"><p className="eyebrow">Platform control</p><h2>Your operational overview</h2><p>Monitor student activity and keep opportunities, learning content, and events current.</p><span className="admin-overview-status"><i /> Workspace snapshot</span></div><div className="admin-overview-brief" aria-label="Platform launch readiness"><div className="admin-brief-orbit" style={{ "--brief-progress": `${launchProgress * 3.6}deg` }}><div><b>{counts ? `${launchReady}/3` : "—"}</b><small>ready</small></div></div><div className="admin-brief-copy"><p className="eyebrow">OPERATIONS PULSE</p><h3>{counts ? launchReady === 3 ? "Your core experience is live." : "Keep the core experience moving." : "Checking platform readiness…"}</h3><p>{counts ? launchReady === 3 ? "Jobs, resources, and events are all ready for students to discover." : "Complete the remaining essentials to give students a stronger workspace." : "Preparing your platform health snapshot."}</p><div className="admin-brief-checklist">{launchSteps.map(([label, done]) => <span className={done ? "done" : ""} key={label}><i>{done ? "✓" : ""}</i>{label}</span>)}</div></div></div></div>{notice && <p className="form-error">{notice}</p>}<section className="metric-grid admin-metrics">{cards.map(([label, value, Icon]) => <article key={label}><span><Icon size={19} /></span><p>{label}</p><strong>{counts ? value : "…"}</strong></article>)}</section><section className="dashboard-grid"><div className="content-card recent-panel"><div className="list-heading"><h3>Recent applications</h3><button className="text-button" onClick={() => go("/admin/applications")}>View all</button></div>{applications.length ? <div className="application-list">{applications.map((item) => <article key={item.id}><div><b>{item.studentName} <small>applied for</small> {item.jobTitle}</b><small>{item.companyName} · {formatDate(item.appliedAt)}</small></div><Status value={item.status} /></article>)}</div> : <p className="muted">No student applications have been submitted yet.</p>}</div><aside className="admin-quick"><p className="eyebrow">Quick actions</p><h3>Keep CareerForge useful.</h3><button onClick={() => go("/admin/jobs")}>Add a job <Plus size={15} /></button><button onClick={() => go("/admin/resources")}>Publish a resource <BookOpen size={15} /></button><button onClick={() => go("/admin/events")}>Create an event <CalendarDays size={15} /></button></aside></section></section>;
}

export function AdminStudents() {
  const [students, setStudents] = useState([]); const [query, setQuery] = useState(""); const [notice, setNotice] = useState(""); const [working, setWorking] = useState(null); const [photoErrors, setPhotoErrors] = useState({});
  const load = () => fetch(`${API_BASE_URL}/admin/students`, { headers: headers() }).then(body).then(setStudents).catch((error) => setNotice(error.message));
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => students.filter((student) => `${student.name} ${student.email} ${student.university || ""} ${student.targetRole || ""}`.toLowerCase().includes(query.toLowerCase())), [students, query]);
  async function toggle(student) { const status = student.status === "active" ? "suspended" : "active"; if (!window.confirm(`${status === "suspended" ? "Suspend" : "Reactivate"} ${student.name}'s account?`)) return; setWorking(student.id); try { await body(await fetch(`${API_BASE_URL}/admin/students/${student.id}/status`, { method: "PUT", headers: headers(), body: JSON.stringify({ status }) })); setStudents((items) => items.map((item) => item.id === student.id ? { ...item, status } : item)); setNotice(`${student.name}'s account is now ${status}.`); } catch (error) { setNotice(error.message); } finally { setWorking(null); } }
  const studentRows = filtered.map((student) => {
    const photoUrl = typeof student.profilePhotoUrl === "string" && student.profilePhotoUrl.trim() ? (student.profilePhotoUrl.startsWith("/") ? `${API_BASE_URL}${student.profilePhotoUrl}` : student.profilePhotoUrl) : "";
    return <article key={student.id}><div className="person"><span className="student-list-avatar">{photoUrl && !photoErrors[student.id] ? <img src={photoUrl} alt={`${student.name}'s profile`} onError={() => setPhotoErrors((current) => ({ ...current, [student.id]: true }))} /> : student.name?.slice(0, 1)?.toUpperCase()}</span><div className="student-list-identity"><b>{student.name}</b><small>{student.email}</small></div></div><div><b>{student.targetRole || "Career direction not added"}</b><small>{student.university || "Profile not completed"}</small></div><Status value={student.status} /><div className="table-actions"><button className={student.status === "active" ? "danger-action" : "success-action"} disabled={working === student.id} onClick={() => toggle(student)}>{working === student.id ? "Saving..." : student.status === "active" ? "Suspend" : "Reactivate"}</button></div></article>;
  });
  return <section className="admin-page"><div className="content-intro compact"><div><p className="eyebrow"><Users size={14} /> User administration</p><h2>View and manage student accounts.</h2><p>Suspend an account to prevent sign in. Reactivate it when the account is ready to use again.</p></div><span className="admin-total">{students.length} users</span></div><div className="table-toolbar"><label><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email, university..." /></label></div>{notice && <p className={notice.includes("now") ? "form-success" : "form-error"}>{notice}</p>}<section className="content-card"><div className="list-heading"><h3>User directory</h3><span>{filtered.length} shown</span></div>{filtered.length ? <div className="admin-table student-table">{studentRows}</div> : <p className="muted">No user matches this search.</p>}</section></section>;
  /* Legacy row markup retained below only to preserve the source layout during this visual migration.
  return <section className="admin-page"><div className="content-intro compact"><div><p className="eyebrow"><Users size={14} /> Student administration</p><h2>View and manage student accounts.</h2><p>Suspend an account to prevent sign in. Reactivate it when the account is ready to use again.</p></div><span className="admin-total">{students.length} students</span></div><div className="table-toolbar"><label><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email, university…" /></label></div>{notice && <p className={notice.includes("now") ? "form-success" : "form-error"}>{notice}</p>}<section className="content-card"><div className="list-heading"><h3>Student directory</h3><span>{filtered.length} shown</span></div>{filtered.length ? <div className="admin-table student-table">{filtered.map((student) => <article key={student.id}><div className="person"><span>{student.name?.slice(0, 1)?.toUpperCase()}</span><div><b>{student.name}</b><small>{student.email}</small></div></div><div><b>{student.targetRole || "Career direction not added"}</b><small>{student.university || "Profile not completed"}</small></div><Status value={student.status} /><div className="table-actions"><button className={student.status === "active" ? "danger-action" : "success-action"} disabled={working === student.id} onClick={() => toggle(student)}>{working === student.id ? "Saving…" : student.status === "active" ? "Suspend" : "Reactivate"}</button></div></article>)}</div> : <p className="muted">No student matches this search.</p>}</section></section>;
  */
}

export function AdminApplications() {
  const [applications, setApplications] = useState([]); const [notice, setNotice] = useState(""); const [savingId, setSavingId] = useState(null);
  useEffect(() => { fetch(`${API_BASE_URL}/admin/applications`, { headers: headers() }).then(body).then(setApplications).catch((error) => setNotice(error.message)); }, []);
  async function updateStatus(id, status) { setSavingId(id); try { await body(await fetch(`${API_BASE_URL}/admin/applications/${id}/status`, { method: "PUT", headers: headers(), body: JSON.stringify({ status }) })); setApplications((items) => items.map((item) => item.id === id ? { ...item, status } : item)); setNotice("Application status updated."); } catch (error) { setNotice(error.message); } finally { setSavingId(null); } }
  return <section className="admin-page"><div className="content-intro compact"><div><p className="eyebrow"><FileText size={14} /> Application records</p><h2>Review applicants and move them forward.</h2><p>Update each application from submitted to under review, shortlisted, rejected, or cancelled.</p></div><span className="admin-total">{applications.length} applications</span></div>{notice && <p className={notice.includes("updated") ? "form-success" : "form-error"}>{notice}</p>}<section className="content-card"><div className="list-heading"><h3>Applications</h3><span>All records</span></div>{applications.length ? <div className="admin-table application-table">{applications.map((item) => <article key={item.id}><div><b>{item.studentName}</b><small>{item.studentEmail}</small></div><div><b>{item.jobTitle}</b><small>{item.companyName} · {item.matchPercentage ?? "—"}% match</small></div><div><small>Submitted</small><b>{formatDate(item.appliedAt)}</b></div><label className="application-status-select"><span>Status</span><select value={item.status} disabled={savingId === item.id} onChange={(event) => updateStatus(item.id, event.target.value)}><option value="submitted">Submitted</option><option value="under_review">Under review</option><option value="shortlisted">Shortlisted</option><option value="rejected">Rejected</option><option value="cancelled">Cancelled</option></select></label></article>)}</div> : <p className="muted">No applications have been submitted yet.</p>}</section></section>;
}

const configurations = {
  assessments: { title: "Assessments", eyebrow: "Assessment management", description: "Create assessments students can take to demonstrate their skills.", icon: ClipboardCheck, blank: { title: "", description: "", category: "Technical", difficulty: "beginner", durationMinutes: 15, passingPercentage: 60, status: "draft" } },
  resources: { title: "Resources", eyebrow: "Learning resource management", description: "Publish useful learning materials and make your strongest picks easy for students to recognise.", icon: BookOpen, blank: { title: "", description: "", category: "Career", type: "article", resourceUrl: "", thumbnailUrl: "", providerName: "", featured: false, recommendationNote: "", estimatedMinutes: "", status: "draft" } },
  events: { title: "Events", eyebrow: "Event management", description: "Create career workshops, employer sessions, and other student events.", icon: CalendarDays, blank: { title: "", description: "", category: "Workshop", location: "", eventUrl: "", startsAt: "", endsAt: "", capacity: "", status: "draft" } },
};

export function AdminContentManager({ kind }) {
  const config = configurations[kind]; const Icon = config.icon; const [items, setItems] = useState([]); const [form, setForm] = useState(config.blank); const [editingId, setEditingId] = useState(null); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false); const [importing, setImporting] = useState(false); const [importQuery, setImportQuery] = useState("software development"); const [importDialogOpen, setImportDialogOpen] = useState(false); const importedDraftsRef = useRef(null);
  const load = () => fetch(`${API_BASE_URL}/admin/content/${kind}`, { headers: headers() }).then(body).then(setItems).catch((error) => setNotice(error.message));
  useEffect(() => { setForm(config.blank); setEditingId(null); setNotice(""); load(); }, [kind]);
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  async function save(event) { event.preventDefault(); setSaving(true); setNotice(""); try { await body(await fetch(`${API_BASE_URL}/admin/content/${kind}${editingId ? `/${editingId}` : ""}`, { method: editingId ? "PUT" : "POST", headers: headers(), body: JSON.stringify({ ...form, durationMinutes: form.durationMinutes ? Number(form.durationMinutes) : null, passingPercentage: form.passingPercentage ? Number(form.passingPercentage) : null, estimatedMinutes: form.estimatedMinutes ? Number(form.estimatedMinutes) : null, capacity: form.capacity ? Number(form.capacity) : null }) })); setNotice(editingId ? "Item updated." : "Item created."); setForm(config.blank); setEditingId(null); load(); } catch (error) { setNotice(error.message); } finally { setSaving(false); } }
  async function importResources(event) { event.preventDefault(); const requested = importQuery.trim(); if (!requested) return; setImportQuery(requested); setImporting(true); setNotice(""); try { const result = await body(await fetch(`${API_BASE_URL}/admin/resources/import?query=${encodeURIComponent(requested)}`, { method: "POST", headers: headers() })); setNotice(`${result.imported} YouTube playlist${result.imported === 1 ? "" : "s"} imported as drafts. Review and publish the ones you approve.`); setImportDialogOpen(false); await load(); window.requestAnimationFrame(() => importedDraftsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" })); } catch (error) { setNotice(error.message); } finally { setImporting(false); } }
  const closeImportDialog = () => { if (importing) return; setImportDialogOpen(false); window.requestAnimationFrame(() => window.scrollTo({ top: 0, behavior: "smooth" })); };
  function edit(item) { setEditingId(item.id); setForm({ ...config.blank, ...item, startsAt: item.startsAt ? String(item.startsAt).slice(0, 16) : "", endsAt: item.endsAt ? String(item.endsAt).slice(0, 16) : "" }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function remove(id) { if (!window.confirm("Delete this item permanently?")) return; try { await body(await fetch(`${API_BASE_URL}/admin/content/${kind}/${id}`, { method: "DELETE", headers: headers() })); setNotice("Item deleted."); load(); } catch (error) { setNotice(error.message); } }
  const text = (label, name, type = "text", placeholder = "", required = false) => <label>{label}<input name={name} type={type} value={form[name] ?? ""} onChange={change} placeholder={placeholder} required={required} /></label>;
  const canPreviewResource = kind === "resources" && isSafeExternalUrl(form.resourceUrl);
  const importedYouTubeDrafts = kind === "resources" ? items.filter((item) => item.status === "draft" && isYouTubeResource(item)) : [];
  const publishedResources = kind === "resources" ? items.filter((item) => item.status === "published") : [];
  const otherResources = kind === "resources" ? items.filter((item) => !importedYouTubeDrafts.includes(item) && !publishedResources.includes(item)) : [];
  const resourceRow = (item) => <article key={item.id}>{isSafeExternalUrl(item.resourceUrl) ? <a className="admin-resource-thumbnail-link" href={item.resourceUrl.trim()} target="_blank" rel="noreferrer" title={`Open ${item.title}`}><AdminResourceThumbnail resource={item} /></a> : <AdminResourceThumbnail resource={item} />}<div><b>{item.title}</b><small>{item.category} · {item.featured ? "CareerForge recommendation" : item.type}</small></div><div className="item-description">{item.description || "No description added."}</div><Status value={item.status} /><div className="table-actions"><button type="button" onClick={() => edit(item)} title="Edit">Edit</button><button type="button" onClick={() => remove(item.id)} title="Delete"><Trash2 size={15} /></button></div></article>;
  const resourceSection = (title, description, sectionItems, emptyMessage, sectionRef) => <section className="resource-inventory-section" ref={sectionRef}><div className="resource-inventory-heading"><div><h4>{title}</h4><p>{description}</p></div><span>{sectionItems.length}</span></div>{sectionItems.length ? <div className="content-table resource-content-table">{sectionItems.map(resourceRow)}</div> : <p className="muted resource-inventory-empty">{emptyMessage}</p>}</section>;
  return <section className="admin-page">
    <div className="content-intro compact"><div><p className="eyebrow"><Icon size={14} /> {config.eyebrow}</p><h2>Manage {config.title.toLowerCase()}.</h2><p>{config.description}</p></div>{kind === "resources" && <ActionButton className="quiet" type="button" onClick={() => setImportDialogOpen(true)} disabled={importing}><RefreshCw size={15} />{importing ? "Importing..." : "Import YouTube playlists"}</ActionButton>}<span className="admin-total">{items.length} total</span></div>
    {kind === "resources" && importDialogOpen && <div className="admin-import-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) closeImportDialog(); }}><section className="admin-import-modal" role="dialog" aria-modal="true" aria-labelledby="playlist-import-title"><header><span className="admin-import-modal-icon"><Youtube size={22} /></span><div><p className="eyebrow">YOUTUBE LIBRARY</p><h3 id="playlist-import-title">Find playlists to review.</h3><p>Search a topic and CareerForge will add matching playlists as drafts for your approval.</p></div><button className="admin-import-modal-close" type="button" onClick={closeImportDialog} disabled={importing} aria-label="Close playlist import"><X size={18} /></button></header><form onSubmit={importResources}><label htmlFor="playlist-import-topic">What do you want students to learn?<span className="admin-import-search"><Search size={19} /><input autoFocus id="playlist-import-topic" value={importQuery} onChange={(event) => setImportQuery(event.target.value)} placeholder="e.g. software development, React, SQL" maxLength="120" /></span></label><p className="admin-import-helper"><CheckCircle2 size={15} /> Imported playlists remain drafts until you review and publish them.</p><div className="admin-import-actions"><button className="admin-import-cancel" type="button" onClick={closeImportDialog} disabled={importing}>Cancel</button><ActionButton type="submit" disabled={importing || !importQuery.trim()}><Search size={15} />{importing ? "Searching..." : "Search playlists"}</ActionButton></div></form></section></div>}
    <form className="data-form admin-content-form" onSubmit={save}>
      <div className="form-row-title"><h3>{editingId ? `Edit ${kind.slice(0, -1)}` : `Add ${kind.slice(0, -1)}`}</h3>{editingId && <button className="text-button" type="button" onClick={() => { setEditingId(null); setForm(config.blank); setNotice(""); }}>Cancel editing</button>}</div>
      <div className="form-grid three">{text("Title", "title", "text", "Enter a title", true)}{text("Category", "category", "text", "Category", true)}{kind === "assessments" && <label>Difficulty<select name="difficulty" value={form.difficulty} onChange={change}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label>}{kind === "resources" && <label>Resource type<select name="type" value={form.type} onChange={change}><option value="article">Article</option><option value="video">Video</option><option value="course">Course</option><option value="pdf">PDF</option><option value="template">Template</option></select></label>}{kind === "events" && text("Location", "location", "text", "Dhaka or online")}{kind === "assessments" && text("Duration (minutes)", "durationMinutes", "number", "15", true)}{kind === "assessments" && text("Passing percentage", "passingPercentage", "number", "60", true)}{kind === "resources" && text("Resource URL", "resourceUrl", "url", "https://...", true)}{kind === "resources" && text("Thumbnail image URL", "thumbnailUrl", "url", "Optional image URL")}{kind === "resources" && text("Provider or channel", "providerName", "text", "e.g. YouTube or freeCodeCamp")}{kind === "resources" && text("Estimated minutes", "estimatedMinutes", "number", "Optional")}{kind === "resources" && <label className="admin-feature-toggle"><input type="checkbox" checked={Boolean(form.featured)} onChange={(event) => setForm({ ...form, featured: event.target.checked })} /><span><b>CareerForge recommendation</b><small>Show this resource first to students.</small></span></label>}{kind === "events" && text("Start date and time", "startsAt", "datetime-local", "", true)}{kind === "events" && text("End date and time", "endsAt", "datetime-local", "", true)}{kind === "events" && text("Capacity", "capacity", "number", "Optional")}{kind === "events" && text("Event URL", "eventUrl", "url", "Optional")}<label>Status<select name="status" value={form.status} onChange={change}><option value="draft">Draft</option><option value="published">Published</option>{kind === "events" ? <option value="cancelled">Cancelled</option> : <option value="archived">Archived</option>}</select></label></div>
      {canPreviewResource && <div className="admin-resource-preview"><AdminResourceThumbnail resource={form} preview /><div><b>{isYouTubeResource(form) ? "YouTube preview" : "Resource preview"}</b><small>{editingId ? "Check the live destination before updating this resource." : "Check the destination before creating this resource."}</small><a href={form.resourceUrl.trim()} target="_blank" rel="noreferrer">{isYouTubeResource(form) ? "Open on YouTube" : "Open resource"} <ExternalLink size={14} /></a></div></div>}
      <label className="full-field">Description<textarea name="description" value={form.description ?? ""} onChange={change} rows="4" placeholder="Explain what students should expect..." /></label>{kind === "resources" && <label className="full-field">Why CareerForge recommends it<textarea name="recommendationNote" value={form.recommendationNote ?? ""} onChange={change} rows="2" placeholder="e.g. A practical starting point for students learning React." /></label>}{notice && <p className={/(created|updated|deleted|imported)/.test(notice) ? "form-success" : "form-error"}>{notice}</p>}<ActionButton type="submit" disabled={saving}><Save size={15} />{saving ? "Saving..." : editingId ? "Update item" : "Create item"}</ActionButton>
    </form>
    <section className="content-card">
      {kind === "resources" ? <div className="resource-inventory-groups">
        {resourceSection("Imported YouTube drafts", "Review these imported playlists, then edit and publish the ones you approve.", importedYouTubeDrafts, "No YouTube playlists are waiting for review.", importedDraftsRef)}
        {resourceSection("Published resources", "These resources are visible to students.", publishedResources, "No resources have been published yet.")}
        {otherResources.length > 0 && resourceSection("Other resources", "Manual drafts and archived resources stay here.", otherResources, "")}
      </div> : <><div className="list-heading"><h3>All {config.title.toLowerCase()}</h3><span>{items.length} total</span></div>{items.length ? <div className="content-table">{items.map((item) => <article key={item.id}><div><b>{item.title}</b><small>{item.category} · {kind === "events" ? formatDate(item.startsAt) : item.difficulty}</small></div><div className="item-description">{item.description || "No description added."}</div><Status value={item.status} /><div className="table-actions"><button type="button" onClick={() => edit(item)} title="Edit">Edit</button><button type="button" onClick={() => remove(item.id)} title="Delete"><Trash2 size={15} /></button></div></article>)}</div> : <p className="muted">No {config.title.toLowerCase()} yet. Use the form above to create the first one.</p>}</>}
    </section>
  </section>;
}

function LegacyAdminCommunity() {
  const [overview, setOverview] = useState(null); const [posts, setPosts] = useState([]); const [announcement, setAnnouncement] = useState(""); const [notice, setNotice] = useState(""); const [working, setWorking] = useState(null); const [publishing, setPublishing] = useState(false); const [refreshing, setRefreshing] = useState(false);
  const load = async (showFeedback = false) => { setRefreshing(true); try { const [summary, postItems] = await Promise.all([
    fetch(`${API_BASE_URL}/admin/community/overview`, { headers: headers() }).then(body),
    fetch(`${API_BASE_URL}/admin/community/posts`, { headers: headers() }).then(body),
  ]); setOverview(summary); setPosts(postItems); if (showFeedback) setNotice("Community moderation data refreshed."); } catch (error) { setNotice(error.message); } finally { setRefreshing(false); } };
  useEffect(() => { load(); }, []);
  async function setPostStatus(post, status) { const action = status === "removed" ? "hide" : "approve"; if (!window.confirm(`${action[0].toUpperCase()}${action.slice(1)} this community post?`)) return; setWorking(`post-${post.id}-${status}`); try { const updated = await body(await fetch(`${API_BASE_URL}/admin/community/posts/${post.id}/status?status=${status}`, { method: "PUT", headers: headers() })); setPosts((items) => items.map((item) => item.id === updated.id ? updated : item)); await load(); setNotice(status === "removed" ? "Post hidden from the student community." : "Post approved for the student community."); } catch (error) { setNotice(error.message); } finally { setWorking(null); } }
  async function rescan(post) { setWorking(`post-${post.id}-rescan`); try { const updated = await body(await fetch(`${API_BASE_URL}/admin/community/posts/${post.id}/rescan`, { method: "PUT", headers: headers() })); setPosts((items) => items.map((item) => item.id === updated.id ? updated : item)); await load(); setNotice(`Post rescanned. It is now ${updated.status.replaceAll("_", " ")}.`); } catch (error) { setNotice(error.message); } finally { setWorking(null); } }
  async function publish(event) { event.preventDefault(); if (!announcement.trim()) return; setPublishing(true); try { const created = await body(await fetch(`${API_BASE_URL}/admin/community/posts`, { method: "POST", headers: headers(), body: JSON.stringify({ content: announcement }) })); setPosts((items) => [created, ...items]); setAnnouncement(""); setNotice("Your administrator announcement is now visible in the community."); } catch (error) { setNotice(error.message); } finally { setPublishing(false); } }
  const cards = [["Visible posts", overview?.visiblePosts], ["Pending review", overview?.pendingPosts], ["Removed posts", overview?.removedPosts], ["Open reports", overview?.openReports]];
  const pendingPosts = posts.filter((post) => post.status === "pending_review" || post.reportCount > 0); const otherPosts = posts.filter((post) => !pendingPosts.some((pending) => pending.id === post.id));
  const postRows = (items) => items.length ? <div className="admin-table community-admin-table">{items.map((post) => <article key={post.id}><div><b>{post.authorName}</b><small>{formatDate(post.createdAt)} · {post.likeCount} likes · {post.commentCount} comments · {post.reportCount} open reports</small></div><p>{post.content}</p><div><Status value={post.status} /><small className="risk-detail">{post.riskLabel} · risk {post.riskScore}/100<br />{post.riskReasons || "No risk signals"}</small></div><div className="table-actions"><button disabled={working === `post-${post.id}`} onClick={() => setPostStatus(post, "visible")}>Approve</button><button className="danger-action" disabled={working === `post-${post.id}`} onClick={() => setPostStatus(post, "removed")}>Remove</button><button disabled={working === `post-${post.id}`} onClick={() => rescan(post)}>Rescan</button></div></article>)}</div> : <p className="muted">Nothing is waiting in this section.</p>;
  return <section className="admin-page admin-community-page"><div className="content-intro compact"><div><p className="eyebrow"><Users size={14} /> Community administration</p><h2>Moderate posts and share official updates.</h2><p>Pending cases are kept separate. You can publish announcements, advice, opportunities, and other community updates without student point limits.</p></div><ActionButton className="quiet" type="button" onClick={load}><RefreshCw size={15} /> Refresh</ActionButton></div>{notice && <p className={/(approved|hidden|rescanned|visible|removed)/i.test(notice) ? "form-success" : "form-error"}>{notice}</p>}<section className="metric-grid admin-metrics community-metrics">{cards.map(([label, value]) => <article key={label}><p>{label}</p><strong>{overview ? value : "…"}</strong></article>)}</section><form className="data-form admin-announcement" onSubmit={publish}><div className="form-row-title"><div><p className="eyebrow">Administrator post</p><h3>Share an official update</h3></div><span className="status visible">No point limit</span></div><textarea value={announcement} onChange={(event) => setAnnouncement(event.target.value)} maxLength="5000" placeholder="Write an announcement, advice, opportunity, or community update…" required /><ActionButton type="submit" disabled={publishing || !announcement.trim()}><Plus size={15} />{publishing ? "Publishing…" : "Publish to community"}</ActionButton></form><section className="content-card moderation-section pending-section"><div className="list-heading"><div><h3>Pending cases</h3><small>Posts awaiting review or with open reports.</small></div><span>{pendingPosts.length} pending</span></div>{postRows(pendingPosts)}</section><section className="content-card moderation-section"><div className="list-heading"><div><h3>Published and removed posts</h3><small>Review all other community activity separately from the pending queue.</small></div><span>{otherPosts.length} posts</span></div>{postRows(otherPosts)}</section></section>;
}
